require 'rails_helper'

RSpec.describe EmailCampaigns::RecipientImporter do
  let(:campaign) { create(:email_campaign) }
  let(:import) { campaign.email_campaign_imports.create! }

  it 'imports the production regression shape NOME;E-MAIL;CORRETORA without changing the file' do
    csv = "NOME;E-MAIL;CORRETORA\nAna;ana@example.org;Alpha\nBia;bia@example.org;Beta\n"

    result = described_class.new(campaign, csv, filename: 'lista de teste chat2you.csv', import: import).perform

    expect(result.to_h.slice(:imported, :invalid, :duplicates, :suppressed, :total)).to eq(
      imported: 2, invalid: 0, duplicates: 0, suppressed: 0, total: 2
    )
    expect(campaign.email_campaign_recipients.order(:email).pluck(:name, :email, :custom_data)).to eq([
                                                                                                        ['Ana', 'ana@example.org',
                                                                                                         { 'corretora' => 'Alpha' }],
                                                                                                        ['Bia', 'bia@example.org',
                                                                                                         { 'corretora' => 'Beta' }]
                                                                                                      ])
    expect(import.reload.schema_resolution).to include(
      'method' => 'deterministic', 'delimiter' => ';', 'email_column' => 1, 'name_column' => 0
    )
  end

  it 'imports an email-only file because recipient name is optional' do
    result = described_class.new(campaign, "EMAIL\nana@example.org\nbia@example.org\n", filename: 'emails.csv', import: import).perform

    expect(result.to_h.slice(:imported, :invalid, :total)).to eq(imported: 2, invalid: 0, total: 2)
    expect(campaign.email_campaign_recipients.order(:email).pluck(:name, :email)).to eq([
                                                                                          [nil, 'ana@example.org'], [nil, 'bia@example.org']
                                                                                        ])
  end

  it 'finds the real header below report title lines' do
    csv = "Relatório comercial\nGerado em 29/09/2026\n\nNOME;E-MAIL;UF\nAna;ana@example.org;MG\n"

    result = described_class.new(campaign, csv, filename: 'relatorio.csv', import: import).perform

    expect(result.imported).to eq(1)
    recipient = campaign.email_campaign_recipients.sole
    expect([recipient.name, recipient.email, recipient.custom_data]).to eq(['Ana', 'ana@example.org', { 'uf' => 'MG' }])
    expect(import.reload.schema_resolution['header_row']).to eq(4)
  end

  it 'imports a Windows-1252 semicolon file without corrupting accents' do
    csv = "NOME;E-MAIL;CIDADE\nJoão;joao@example.org;São Paulo\n".encode(Encoding::Windows_1252)

    result = described_class.new(campaign, csv, filename: 'excel.csv', import: import).perform

    expect(result.imported).to eq(1)
    recipient = campaign.email_campaign_recipients.sole
    expect([recipient.name, recipient.custom_data]).to eq(['João', { 'cidade' => 'São Paulo' }])
  end

  it 'selects the recipient sheet from a multi-sheet XLSX and ignores instructions and summaries' do
    xlsx = build_xlsx_sheets(
      'Instruções' => [['Não altere este relatório']],
      'Resumo' => [%w[CAMPO VALOR], %w[TOTAL 2]],
      'BASE CLIENTES' => [%w[NOME EMAIL CORRETORA], ['Ana', 'ana@example.org', 'ABC'], ['Bia', 'bia@example.org', 'XYZ']]
    )

    result = described_class.new(campaign, xlsx, filename: 'clientes.xlsx', import: import).perform

    expect(result.imported).to eq(2)
    expect(campaign.email_campaign_recipients.order(:email).pluck(:email)).to eq(%w[ana@example.org bia@example.org])
    expect(import.reload.schema_resolution).to include('format' => 'xlsx', 'table_index' => 2, 'email_column' => 1)
  end

  it 'imports a real XLSX package generated by Excel-compatible tooling with title rows and multiple sheets' do
    fixture = Rails.root.join('spec/fixtures/files/email_campaign_import/real_excel_multisheet.xlsx')
    xlsx = File.binread(fixture)

    result = described_class.new(campaign, xlsx, filename: 'real_excel_multisheet.xlsx', import: import).perform

    expect(result.imported).to eq(2)
    expect(campaign.email_campaign_recipients.order(:email).pluck(:name, :email, :custom_data)).to eq(
      [
        ['Bia Souza', 'bia@example.org', { 'corretora' => 'Beta' }],
        ['João da Silva', 'joao@example.org', { 'corretora' => 'Alpha' }]
      ]
    )
    expect(import.reload.schema_resolution).to include('format' => 'xlsx', 'table_index' => 2, 'header_row' => 4)
  end

  it 'imports 20,000 valid rows through the real database path' do
    rows = (1..20_000).map { |index| "Pessoa #{index},pessoa#{index}@example.org" }.join("\n")
    csv = "NOME,EMAIL\n#{rows}\n"

    result = described_class.new(campaign, csv, filename: '20k.csv', import: import).perform

    expect(result.to_h.slice(:imported, :invalid, :duplicates, :suppressed, :total)).to eq(
      imported: 20_000, invalid: 0, duplicates: 0, suppressed: 0, total: 20_000
    )
    expect(campaign.email_campaign_recipients.count).to eq(20_000)
  end

  it 'imports exactly 50,000 valid rows at the supported limit' do
    rows = (1..50_000).map { |index| "Pessoa #{index},limite#{index}@example.org" }.join("\n")
    csv = "NOME,EMAIL\n#{rows}\n"

    result = described_class.new(campaign, csv, filename: '50k.csv', import: import).perform

    expect(result.to_h.slice(:imported, :invalid, :duplicates, :suppressed, :total)).to eq(
      imported: 50_000, invalid: 0, duplicates: 0, suppressed: 0, total: 50_000
    )
    expect(campaign.email_campaign_recipients.count).to eq(50_000)
  end

  it 'rejects 50,001 data rows before inserting any recipient' do
    rows = (1..50_001).map { |index| "Pessoa #{index},pessoa#{index}@example.org" }.join("\n")
    csv = "NOME,EMAIL\n#{rows}\n"

    expect do
      described_class.new(campaign, csv, filename: 'too-large.csv', import: import).prepare
    end.to raise_error(described_class::Error, 'row_limit_exceeded')
    expect(campaign.email_campaign_recipients).not_to exist
  end
end
