// Guia da Plataforma — rotas para onde ele pode levar o usuário.
//
// ARQUIVO GERADO por `pnpm guia:build` a partir do roteador do painel. Não edite à mão.
// Defesa em profundidade: o Guia só sugere navegação a partir do mapa, e o painel só
// navega se o nome estiver AQUI E resolver no roteador E a pessoa tiver permissão.
export const GUIDE_ROUTE_REGISTRY = new Set([
  'account_overview_reports',
  'account_suspended',
  'agent_assignment_policy_create',
  'agent_assignment_policy_edit',
  'agent_assignment_policy_index',
  'agent_bots',
  'agent_capacity_policy_create',
  'agent_capacity_policy_edit',
  'agent_capacity_policy_index',
  'agent_list',
  'agent_reports',
  'agent_reports_index',
  'agent_reports_show',
  'assignment_policy_index',
  'attributes_list',
  'auditlogs_list',
  'automation_list',
  'autonomia_agent_panel',
  'autonomia_agents_builder',
  'autonomia_agents_index',
  'autonomia_financial_invoices',
  'autonomia_financial_subscription',
  'autonomia_insurance',
  'autonomia_insurance_agent',
  'autonomia_insurance_connections',
  'autonomia_invite_connection',
  'autonomia_prospecting_lists',
  'autonomia_prospecting_search',
  'autonomia_prospecting_settings',
  'billing_settings_index',
  'bot_reports',
  'calls_dashboard_index',
  'campaigns_email_builder',
  'campaigns_email_index',
  'campaigns_email_sender_index',
  'campaigns_email_templates',
  'campaigns_livechat_index',
  'campaigns_one_off_index',
  'campaigns_ongoing_index',
  'campaigns_sms_index',
  'campaigns_whatsapp_analytics',
  'campaigns_whatsapp_api_index',
  'campaigns_whatsapp_index',
  'canned_list',
  'captain_assistants_create_index',
  'captain_assistants_documents_index',
  'captain_assistants_faq_suggestions',
  'captain_assistants_guardrails_index',
  'captain_assistants_guidelines_index',
  'captain_assistants_inboxes_index',
  'captain_assistants_index',
  'captain_assistants_overview_index',
  'captain_assistants_playground_index',
  'captain_assistants_responses_index',
  'captain_assistants_scenarios_index',
  'captain_assistants_settings_audience_index',
  'captain_assistants_settings_index',
  'captain_assistants_settings_schedule_index',
  'captain_assistants_settings_system_index',
  'captain_settings_index',
  'captain_tools_index',
  'companies_dashboard_index',
  'companies_dashboard_show',
  'contacts_campaign_imports',
  'contacts_dashboard_active',
  'contacts_dashboard_index',
  'contacts_dashboard_labels_index',
  'contacts_dashboard_segments_index',
  'contacts_edit',
  'contacts_edit_label',
  'contacts_edit_segment',
  'conversation_mentions',
  'conversation_participating',
  'conversation_reports',
  'conversation_through_inbox',
  'conversation_through_mentions',
  'conversation_through_participating',
  'conversation_through_unattended',
  'conversation_unattended',
  'conversation_workflow_index',
  'conversations_through_folders',
  'conversations_through_label',
  'conversations_through_team',
  'crm_ai_usage_index',
  'crm_calendar_index',
  'crm_campaign_management_index',
  'crm_dashboard_index',
  'crm_handoff_settings_edit',
  'crm_handoff_settings_index',
  'crm_integration_tokens_index',
  'crm_kanban_index',
  'crm_sla_index',
  'csat_reports',
  'custom_roles_list',
  'first_steps',
  'folder_conversations',
  'general_settings_index',
  'home',
  'inbox_conversation',
  'inbox_dashboard',
  'inbox_reports',
  'inbox_reports_index',
  'inbox_reports_show',
  'inbox_view',
  'inbox_view_conversation',
  'label_conversations',
  'label_reports',
  'label_reports_index',
  'label_reports_show',
  'labels_list',
  'labels_wrapper',
  'macros_edit',
  'macros_new',
  'macros_wrapper',
  'no_accounts',
  'onboarding_account_details',
  'onboarding_inbox_setup',
  'portals_articles_edit',
  'portals_articles_index',
  'portals_articles_new',
  'portals_categories_articles_edit',
  'portals_categories_articles_index',
  'portals_categories_articles_new',
  'portals_categories_index',
  'portals_index',
  'portals_locales_index',
  'portals_new',
  'portals_settings_index',
  'profile_settings',
  'profile_settings_index',
  'profile_settings_mfa',
  'search',
  'security_settings_index',
  'settings_applications',
  'settings_applications_integration',
  'settings_data_import_show',
  'settings_data_imports',
  'settings_home',
  'settings_inbox_finish',
  'settings_inbox_list',
  'settings_inbox_new',
  'settings_inbox_show',
  'settings_inboxes_add_agents',
  'settings_inboxes_page_channel',
  'settings_integrations_crm_n8n',
  'settings_integrations_dashboard_apps',
  'settings_integrations_linear',
  'settings_integrations_notion',
  'settings_integrations_shopify',
  'settings_integrations_slack',
  'settings_integrations_webhook',
  'settings_prospecting_index',
  'settings_teams_add_agents',
  'settings_teams_edit',
  'settings_teams_edit_finish',
  'settings_teams_edit_members',
  'settings_teams_finish',
  'settings_teams_list',
  'settings_teams_new',
  'settings_templates',
  'sla_reports',
  'team_conversations',
  'team_reports',
  'team_reports_index',
  'team_reports_show',
]);

// Telas que dependem de uma feature: sem ela ligada na conta, o Guia não oferece o
// botão — o backend negaria a tela e a pessoa cairia num beco.
export const GUIDE_ROUTE_FEATURES = {
  account_overview_reports: 'reports',
  agent_assignment_policy_create: 'assignment_v2',
  agent_assignment_policy_edit: 'assignment_v2',
  agent_assignment_policy_index: 'assignment_v2',
  agent_bots: 'agent_bots',
  agent_capacity_policy_create: 'advanced_assignment',
  agent_capacity_policy_edit: 'advanced_assignment',
  agent_capacity_policy_index: 'advanced_assignment',
  agent_list: 'agent_management',
  agent_reports: 'reports',
  agent_reports_index: 'reports',
  agent_reports_show: 'reports',
  assignment_policy_index: 'assignment_v2',
  attributes_list: 'custom_attributes',
  auditlogs_list: 'audit_logs',
  automation_list: 'automations',
  bot_reports: 'reports',
  campaigns_email_builder: 'campaigns',
  campaigns_email_index: 'campaigns',
  campaigns_email_sender_index: 'campaigns',
  campaigns_email_templates: 'campaigns',
  campaigns_livechat_index: 'campaigns',
  campaigns_one_off_index: 'campaigns',
  campaigns_ongoing_index: 'campaigns',
  campaigns_sms_index: 'campaigns',
  campaigns_whatsapp_analytics: 'whatsapp_campaign',
  campaigns_whatsapp_api_index: 'campaigns',
  campaigns_whatsapp_index: 'whatsapp_campaign',
  canned_list: 'canned_responses',
  captain_assistants_documents_index: 'captain_integration',
  captain_assistants_faq_suggestions: 'captain_integration',
  captain_assistants_guardrails_index: 'captain_integration_v2',
  captain_assistants_guidelines_index: 'captain_integration_v2',
  captain_assistants_inboxes_index: 'captain_integration',
  captain_assistants_index: 'captain_integration',
  captain_assistants_overview_index: 'captain_integration',
  captain_assistants_playground_index: 'captain_integration',
  captain_assistants_responses_index: 'captain_integration',
  captain_assistants_scenarios_index: 'captain_integration_v2',
  captain_assistants_settings_audience_index: 'captain_integration',
  captain_assistants_settings_index: 'captain_integration',
  captain_assistants_settings_schedule_index: 'captain_integration',
  captain_assistants_settings_system_index: 'captain_integration',
  captain_settings_index: 'captain_integration',
  captain_tools_index: 'custom_tools',
  companies_dashboard_index: 'companies',
  companies_dashboard_show: 'companies',
  contacts_campaign_imports: 'crm',
  contacts_dashboard_active: 'crm',
  contacts_dashboard_index: 'crm',
  contacts_dashboard_labels_index: 'crm',
  contacts_dashboard_segments_index: 'crm',
  contacts_edit: 'crm',
  contacts_edit_label: 'crm',
  contacts_edit_segment: 'crm',
  conversation_reports: 'reports',
  crm_handoff_settings_edit: 'crm',
  crm_handoff_settings_index: 'crm',
  crm_sla_index: 'sla',
  csat_reports: 'reports',
  custom_roles_list: 'custom_roles',
  inbox_reports: 'reports',
  inbox_reports_index: 'reports',
  inbox_reports_show: 'reports',
  label_reports: 'reports',
  label_reports_index: 'reports',
  label_reports_show: 'reports',
  labels_list: 'labels',
  macros_edit: 'macros',
  macros_new: 'macros',
  macros_wrapper: 'macros',
  portals_articles_edit: 'help_center',
  portals_articles_index: 'help_center',
  portals_articles_new: 'help_center',
  portals_categories_articles_edit: 'help_center',
  portals_categories_articles_index: 'help_center',
  portals_categories_articles_new: 'help_center',
  portals_categories_index: 'help_center',
  portals_index: 'help_center',
  portals_locales_index: 'help_center',
  portals_new: 'help_center',
  portals_settings_index: 'help_center',
  security_settings_index: 'saml',
  settings_applications: 'integrations',
  settings_applications_integration: 'integrations',
  settings_data_import_show: 'data_import',
  settings_data_imports: 'data_import',
  settings_inbox_finish: 'inbox_management',
  settings_inbox_list: 'inbox_management',
  settings_inbox_new: 'inbox_management',
  settings_inbox_show: 'inbox_management',
  settings_inboxes_add_agents: 'inbox_management',
  settings_inboxes_page_channel: 'inbox_management',
  settings_integrations_crm_n8n: 'integrations',
  settings_integrations_dashboard_apps: 'integrations',
  settings_integrations_shopify: 'integrations',
  settings_integrations_slack: 'integrations',
  settings_integrations_webhook: 'integrations',
  settings_teams_add_agents: 'team_management',
  settings_teams_edit: 'team_management',
  settings_teams_edit_finish: 'team_management',
  settings_teams_edit_members: 'team_management',
  settings_teams_finish: 'team_management',
  settings_teams_list: 'team_management',
  settings_teams_new: 'team_management',
  sla_reports: 'sla',
  team_reports: 'reports',
  team_reports_index: 'reports',
  team_reports_show: 'reports',
};

export const isGuideRoute = name => GUIDE_ROUTE_REGISTRY.has(name);

export const guideRouteFeature = name => GUIDE_ROUTE_FEATURES[name] || null;

export default GUIDE_ROUTE_REGISTRY;
