# == Schema Information
#
# Table name: campaign_reply_codes
#
#  id            :bigint           not null, primary key
#  campaign_type :string           not null
#  code          :string           not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  account_id    :bigint           not null
#  campaign_id   :bigint           not null
#
# Indexes
#
#  index_campaign_reply_codes_on_account_id                      (account_id)
#  index_campaign_reply_codes_on_campaign_type_and_campaign_id  (campaign_type,campaign_id) UNIQUE
#  index_campaign_reply_codes_on_code                            (code) UNIQUE
#
# Foreign Keys
#
#  fk_rails_...  (account_id => accounts.id) ON DELETE => cascade
#
# Campaign reply code (#1002): the #CODE of a campaign's "talk on WhatsApp" button. Same
# alphabet and length as a tracked link code, so Ctwa::TrackedLinkAttributor reads both with
# the parsing it already has. Generated by CampaignJourney::ReplyCodes.
class CampaignReplyCode < ApplicationRecord
  belongs_to :account
  belongs_to :campaign, polymorphic: true

  validates :code, presence: true, uniqueness: true, format: { with: Ctwa::TrackedLink::CODE_FORMAT }
  validates :campaign_id, uniqueness: { scope: :campaign_type }
end
